remove(list = ls())
options(stringsAsFactors = FALSE)
options(scipen = 999)

setwd("/Users/harrocyranka/Desktop/rviz/tidy_tuesday_week_20/")
library(tidyverse);library(tidytext)


##Bring and sample data
x <- read_csv("sampled_tweets.csv") %>%
  filter(account_type %in% c("left", "Right") & language == "English")
x <- x %>% mutate(account_type = str_to_title(account_type))

set.seed(1)
x_2 <- x %>% sample_n(20000) %>% dplyr::rename(text = content) %>%
  mutate(text = rtweet::plain_tweets(text)) %>%
  mutate(document = 1:20000)

###
tidy_tweets <- x_2 %>% select(document, account_type,text) %>%
  unnest_tokens(word, text, token = "tweets") %>%
  group_by(word) %>% filter(n() > 10) %>%
  ungroup()

##Create a sparse matrix
sparse_tweets <- tidy_tweets %>% dplyr::count(document, word, sort = TRUE) %>%
  cast_sparse(document, word, n)

tweets_joined  <- data_frame(document = (as.integer(rownames(sparse_tweets)))) %>%
  left_join(x_2) %>% select(document,account_type)

##Fit the model and split the sample
set.seed(1)
train_rows <- sample(1:19660, 15000)

library(glmnet)
response_model <- tweets_joined$account_type == "Right"


lasso_model <- cv.glmnet(sparse_tweets[train_rows,],
                         y = response_model[train_rows],
                         family = "binomial",
                         alpha = 1,
                         nfolds = 10)


##Check coefficients
##Tidying the model
library(broom)

coefficients <- lasso_model$glmnet.fit %>% tidy() %>%
  filter(lambda == lasso_model$lambda.min)


##Training data predictions
test_classification <- tidy_tweets%>% filter(!document %in% train_rows) %>%
  inner_join(coefficients, by = c("word" = "term")) %>%
  dplyr::group_by(document) %>%
  dplyr::summarize(Score = sum(estimate)) %>%
  mutate(probability = arm::invlogit(0.2777646 + Score)) %>%
  mutate(predictions = ifelse(probability > 0.55, "Right", "Left"))%>% ##We can do slightly better by increasing threshold
  inner_join(x_2 %>% select(document, account_type))


##Create confusion matrix
test_classification %>% group_by(predictions, account_type) %>% tally() %>%
  spread(account_type, n)

##Top coefficients
coefficients %>% filter(term!="(Intercept)") %>%
  top_n(n = 15, estimate) %>% arrange(desc(estimate)) %>%
  bind_rows(coefficients %>% filter(term!="(Intercept)") %>%
              top_n(n = -15, estimate) %>% arrange(estimate)) %>% 
  ggplot(aes(x = reorder(term, estimate), y = estimate, fill = estimate >0)) + geom_col(show.legend = FALSE) + coord_flip() + 
  theme_minimal() + 
  labs(x = "Term", y = "Coefficient", title = "Largest and smallest coefficients: Lasso fit") + 
  theme(
    text = element_text(family = "Roboto")
  )


##Get ROC curve: Test set
account_classes <- test_classification %>% mutate(Correct = (predictions == account_type))
original_classifications <- as.numeric(factor(account_classes$account_type)) - 1
predictions <- as.numeric(factor(account_classes$predictions)) - 1
pROC::roc(original_classifications, predictions)


##Predicted right, but actually left
mistakes <- test_classification %>% filter(account_type == "Left" & probability > 0.7)

##Do a word cloud of the mistakes 
x_2 %>% filter(document %in% mistakes$document) %>% 
  select(text) %>% unnest_tokens(word, text, token = "tweets") %>%
  anti_join(stop_words) %>% group_by(word) %>% tally() %>% arrange(desc(n)) %>%
  slice(1:200) %>%
  wordcloud2::wordcloud2(color = "firebrick", fontFamily = "Roboto")

test_classification %>%
  ggplot(aes(x = probability*100, y = ..density.., fill = account_type)) + 
  geom_density(adjust = 4, show.legend = TRUE,alpha = 0.5) + 
  theme_minimal() + 
  theme(legend.position = "bottom",
        legend.title = element_text(face = "bold"),
        plot.title = element_text(size = 14, face = "bold")) + 
  labs(x = "Pr(Y = right-wing | X)", y= "Density",
       title = "Model generated probability of being a right-wing account",
       subtitle = "Probabilities generated by a Lasso model") + 
  scale_fill_manual(values = c("navyblue", "firebrick3")) + 
  guides(fill = guide_legend(title = "Account type", title.position = "top", 
                             title.hjust = 0.5, barwidth = 20,
                             barheight = 0.5,keywidth = 5,keyheight = 0.5,nrow = 1,label.position = "bottom"))


##Building a TF-IDF
