remove(list =ls())
options(stringsAsFactors = FALSE)
options(scipen = 999)

library(tidyverse); library(caret);library(arm)

##
x <- read_csv("Admission_Predict_Ver1.1.csv") %>%
  mutate(log_odds = boot::logit(`Chance of Admit`))


##
replace_spaces_to_lower <- function(x){
  z <- str_replace_all(str_to_lower(x),pattern = "\\s{1,2}",replacement = "_")
  return(z)
}

x <- x %>% rename_all(replace_spaces_to_lower) %>%
  dplyr::select(-chance_of_admit)

##
x_matrix <- x %>% dplyr::select(-`serial_no.`,log_odds) %>%
  mutate_at(c("research", "university_rating"), as.factor)


##Train basic logit
set.seed(4)
rctrl2 <- trainControl(method = "LOOCV")
lm_1 <- caret::train(log_odds~.,data = x_matrix,
                     method = "lm",trControl = rctrl2)

summary(lm_1)

##Generate simulations
set.seed(3)
simulations <- sim(lm_1$finalModel, 1000)

###Simulate GRE
gre_seq <- seq(290,to = 340, by = 1)
gre_numbers <- expand.grid(
            Intercept = 1,
            gre_score = gre_seq,toelfl_score = mean(x_matrix$toefl_score),
            university_rating2 = 0,
            university_rating3 = 1,
            university_rating4 = 0,
            university_rating5 = 0,
            sop = mean(x_matrix$sop),
            lor = mean(x_matrix$lor),
            cgpa = mean(x_matrix$cgpa),
            research1 = 1)

sim_results <- as_data_frame(simulations@coef %*% t(as.matrix(gre_numbers)))
simulation_results <- sim_results %>% gather(score, sim_outcome) %>%
  mutate(score = rep(gre_seq, each = 1000)) %>%
  mutate(sim_number = rep(1:1000,51)) %>%
  mutate(sim_outcome = arm::invlogit(sim_outcome))

avg_sim_gre <- simulation_results %>%
  group_by(score) %>%
  summarise(mean_pred = mean(sim_outcome),
            sd_pred = sd(sim_outcome))

##Simulate GPA
gpa_seq <- seq(6.8,to = 9.9, length.out = 51)
gpa_matrix <- expand.grid(
  Intercept = 1,
  gre_score = mean(x_matrix$gre_score),
  toelfl_score = mean(x_matrix$toefl_score),
  university_rating2 = 0,
  university_rating3 = 1,
  university_rating4 = 0,
  university_rating5 = 0,
  sop = mean(x_matrix$sop),
  lor = mean(x_matrix$lor),
  cgpa = gpa_seq,
  research1 = 1) %>% as_tibble()


sim_gpa <- as_data_frame(simulations@coef %*% t(as.matrix(gpa_matrix)))
gpa_simulation_res <- sim_gpa %>% gather(score, sim_outcome) %>%
  mutate(score = rep(gpa_seq, each = 1000)) %>%
  mutate(sim_number = rep(1:1000,51)) %>%
  mutate(sim_outcome = arm::invlogit(sim_outcome))

avg_sim_gpa <- gpa_simulation_res %>%
  group_by(score) %>%
  summarise(mean_pred = mean(sim_outcome),
            sd_pred = sd(sim_outcome))

##
avg_sim_gpa %>%
  ggplot(aes(x = score, y = mean_pred, ymin = mean_pred - 2*sd_pred,ymax =mean_pred + 2*sd_pred)) + 
  geom_pointrange() + 
  theme_minimal() + 
  labs(x = "GPA score",
       y = "Mean predicted probability",
       title = "Predicted probabilities of admission into graduate school by undergraduate GPA",
       subtitle = "Estimates generated by simulating a logit model\nOther variables held at their means or most common values") + 
  scale_y_continuous(breaks = seq(0.4,1,by = 0.05),
                     labels = scales::percent) + 
  scale_x_continuous(limits = c(6.8, 10),
                     breaks = seq(7,10,by = 0.5)) 


##
round_3 <- function(x){round(x,3)}
lm_1$finalModel %>% broom::tidy() %>% 
  mutate_if(is_double, round_3) %>%
  mutate(term = str_replace_all(term, "\\(|\\)",""),
         term = str_replace_all(term, "university_rating", "University Rating "),
         term = str_replace_all(term, "research1", "U-grad research")) %>%
  mutate(estimate = exp(estimate)) %>%
  filter(term != "Intercept") %>%
  ggplot(aes(x = reorder(term, estimate), y = estimate)) + geom_point(size =2) + 
  geom_col(width = 0.03) + 
  coord_flip() +
  labs(x = "Odds ratio", y = "Variable", title = "Odds ratios for variables in the graduate admission dataset",
       subtitle = "Estimates generated by a logit model") + 
  theme_minimal()