remove(list = ls())
options(stringsAsFactors = FALSE)
options(scipen = 999)

library(tidyverse);library(viridis)
x <- read_csv("baltimore_bridges.csv") %>%
  mutate(county = str_to_title(county))


hfac::describe(x)

##Model
y <- x %>% select(county,owner, yr_built, avg_daily_traffic, bridge_condition) %>%
  group_by(owner) %>% filter(n() > 200) %>% ungroup()

##Change to factor
y <- y %>%
  mutate(county = factor(county),
         owner = factor(owner),
         condition = factor(ifelse(bridge_condition == "Good", "Good", "Other"))) %>%
  select(-bridge_condition)


# Ridge regression --------------------------------------------------------

##Separate into train and validation
set.seed(2)
train_rows <- sample(1:nrow(y), 1628) ##Around 80%

train <- y %>% slice(train_rows)
test <- y %>% slice(-train_rows)

##Create training matrix and set
train_predictors <- y %>% slice(train_rows)
test_predictors <- y %>% slice(-train_rows)

train_matrix <- model.matrix(condition ~.,train_predictors)[,-1]
train_response <- y %>% slice(train_rows) %>% select(condition) %>% pull()

test_matrix <-  model.matrix(condition ~.,test_predictors)[,-1]
test_response <- y %>% slice(-train_rows) %>% select(condition) %>% pull()


##Model fit
library(glmnet)
grid <- 10**seq(10, -2, length= 100)

#fit the model
ridge_model <- glmnet(train_matrix, train_response, alpha = 0, lambda = grid,
                      family ="binomial")


##Cross validate the results
set.seed(2)
cv_out <- cv.glmnet(train_matrix,train_response,alpha=0, family = "binomial")

best_lambda <- cv_out$lambda.min

##Predict on the test set
test_set_predictions <- arm::invlogit(predict(ridge_model, s = best_lambda, newx = test_matrix))

##Basic confusion matrix
y %>% slice(-train_rows) %>% mutate(prediction = test_set_predictions) %>%
  mutate(prediction = ifelse(prediction > 0.5, "Other", "Good")) %>%
  group_by(condition, prediction) %>% tally() %>% spread(condition, n)


# Decision tree ----------------------------------------------------------
library(tree)

tree_condition <- tree(condition~.,data = y, subset = train_rows)
cv_tree <- cv.tree(tree_condition, FUN = prune.misclass)
pruned_tree <- prune.misclass(tree_condition, best =4)

tree_predictions <- predict(pruned_tree, test_predictors, type = "class") 
table(test_predictors$condition, tree_predictions)


plot(pruned_tree,  = "Fitted decision tree model")
text(pruned_tree, cex = 0.8,pretty = 0)


##Where did the model predict correctly?County
lat_long_plot <- y %>% slice(-train_rows) %>% bind_cols(x %>% select(lat, long, county,owner, yr_built, avg_daily_traffic, bridge_condition) %>%
                                         group_by(owner) %>% filter(n() > 200) %>% ungroup() %>%
                                         slice(-train_rows) %>%
                                         select(lat, long)) %>%
  mutate(prediction = tree_predictions) %>%
  mutate(correct = ifelse(condition == prediction,"Correct predictions", "Incorrect predictions"))  


###Map
urbnmapr::counties %>% filter(state_abbv %in% c("MD")) %>% mutate(county_name = str_to_title(county_name)) %>%
  inner_join(lat_long_plot %>% rename(lat1 = lat, long1 = long), by = c("county_name" = "county")) %>%
  ggplot(aes(long, lat, group = group)) + 
  geom_polygon() + 
  geom_polygon(size = .55,color = "gray70", fill = "gray40") +
  theme_minimal() + 
  labs(title = "County visualization of bridge condition predictions on test set",
       subtitle = "Predictions generated by an unpruned decision tree\n",
       caption = "Total bridges on test set = 407\nTest accuracy: 83.0%\nTidy tuesday week 35") + 
  theme(
    text = element_text(family = "Roboto"),
    plot.title = element_text(face = "bold", size = 17),
    plot.subtitle = element_text(size = 13),
    plot.caption = element_text(size = 10),
    legend.position = "bottom",
    legend.text = element_text(size = 13),
    legend.title = element_text(size = 15, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_blank(),
    strip.text = element_text(size = 12, color = "white", face = "bold"),
    strip.background = element_rect(fill = "gray40")
  ) + facet_wrap(~correct) + 
  scale_color_manual(values = c("green", "salmon"))#+ 
  # guides(color = guide_legend(title.position ="top",
  #                             title = "Correct prediction?",
  #                             title.hjust = 0.5,
  #                             label.position = "right",
  #                             label.hjust = 0.5, override.aes = list(size = 3),nrow = 2)) + facet_wrap(~correct)


##Partition space
levels_order <- c("County Highway Agency", "State Toll Authority","City or Municipal Highway Agency",
                  "State Highway Agency")
y %>% slice(-train_rows) %>%
  mutate(prediction = tree_predictions) %>%
  mutate(correct = as.numeric(condition == prediction)) %>%
  ggplot(aes(x = yr_built, y = factor(owner, levels = levels_order), color = factor(correct, labels = c("No", "Yes")))) + 
           geom_jitter(height = 0.2, width = 2, alpha =0.7) + 
  geom_vline(xintercept = 1983,size = 0.2, linetype = 2) + 
  geom_vline(xintercept = 1992,size = 0.2, linetype = 2) + 
  geom_segment(aes(x = 1880, y = 2.5, xend = 1982,yend=2.5),
               linetype = 2, color = "black", size = 0.01) + 
  theme_minimal() + 
  theme(
    text = element_text(family = "Roboto"),
    plot.title = element_text(face = "bold", size = 17),
    plot.subtitle = element_text(size = 13),
    plot.caption = element_text(size = 10),
    legend.position = "bottom",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line.x = element_line(size = 0.5),
    axis.line.y = element_line(size = 0.5)
  ) + 
  labs(x = "\nYear built", y = "Owner",
       title = "Partition of the predictor space by the unpruned tree model",
       subtitle = "Labels refer to model prediction") + 
  scale_x_continuous(breaks = seq(1880, 2010, by = 10)) + 
  annotate(geom = "text", x = 1960, y = 3.5,label = "Not good", size = 3.5) + 
  annotate(geom = "text", x = 1960, y = 1.5,label = "Not good",size = 3.5) + 
  annotate(geom = "text", x = 1987.5, y = 2.5,label = "Good",size = 3.5) + 
  annotate(geom = "text", x = 2000, y = 2.5,label = "Good",size = 3.5) + 
  scale_color_manual(values = c("red", "green")) + 
  guides(color = guide_legend(title.position ="top",
                            title = "Correct prediction?",
                            label.position = "bottom",
                            override.aes = list(size = 3),ncol = 2))


##
y %>% slice(-train_rows) %>%
  mutate(prediction = tree_predictions) %>%
  mutate(correct = ifelse(condition == prediction,"Yes", "No"),
         year_bucket = case_when(yr_built <=1983 ~ "1983 or before",
                                 between(yr_built, 1984, 1992) ~ "Between 1984 and 1992",
                                 TRUE ~ "After 1992")) %>%
  group_by(owner, year_bucket, correct) %>% tally() %>% group_by(owner, year_bucket) %>%
  mutate(percent = n/sum(n)) %>% filter(correct == "Yes") %>%
  ggplot(aes(x = factor(year_bucket,levels = c("1983 or before","Between 1984 and 1992", "After 1992")),
             y= factor(owner, levels = levels_order), fill = percent,
             label = round(percent*100,1))) + geom_text() + 
  geom_tile(color = "black") +
  theme_minimal() + 
  labs(x = "\nYear built", y = "Owner", title = "Test set bridge condition prediction accuracy by owner and year built",
       subtitle = "Predictions generated by an unpruned tree model") + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", size = 17),
    plot.subtitle = element_text(size = 13),
    plot.caption = element_text(size = 10),
    legend.position = "bottom"
  ) + 
  scale_fill_gradient(low = "red", high = "green",breaks = c(0.4,0.6,0.8,1),labels = c("40%", "60%", "80%", "100%")) + 
  guides(fill = guide_colorbar(title = "Accuracy",
                               title.position = "top",
                               title.hjust = 0.5, 
                               barwidth = 10))
  
##
